name: ml046-metrics
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - jupyterlab
  - pip:
      - numpy==2.3.5
      - scipy==1.17.0
      - scikit-learn==1.8.0
      - matplotlib==3.10.8
      - nbformat==5.11.1
      - ipykernel==7.4.0
